<a href="https://colab.research.google.com/github/Dysuza/Datascience/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
A="adith biju"
B="age 10"
C = A + B
print(C)


adith bijuage 10


In [ ]:
A = input("enter your name")
B= input("enter your age")
C= A + B
print(C)

enter your nameAdith
enter your age10
Adith10


In [ ]:
name= input("enter the name0")
print( name )

enter the name0adith
adith


In [ ]:
print(type(name))

<class 'str'>


In [ ]:
# Heading

- blahhh
# Heading1
## Heading2
**bold**
*bold*
***bold***
```
print("Hello world")
```
[Google](https://www.google.com)


In [ ]:
x=10
y=10.55
z=1+2j
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
x= complex(1,2)
x

(1+2j)

In [ ]:
type(x)

complex

In [ ]:
var1= float(input("enter the number:"))
var2= 23.133
print(var1)
print(var2)

enter the number:12
12.0
23.133


In [ ]:
name = "ally the Allien"
name

'ally the Allien'

In [ ]:
greeting="welcome to the Earth !!!!"
message = name + " , " + greeting
message

'ally the Allien , welcome to the Earth !!!!'

In [ ]:
x=123
y=-123
z=4
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
print("blahh"*7)

blahhblahhblahhblahhblahhblahhblahh


In [ ]:
print("blahh\n"*7)

blahh
blahh
blahh
blahh
blahh
blahh
blahh



In [ ]:
forename = input("What is your name?")
print("Hello", forename)

What is your name?adith
Hello adith


In [ ]:
s="python"
print(s[0])
print(s[-3])
print(s[1])
print(len(s))
s[-len(s)]

p
h
y
6


'p'

In [ ]:
s="python"
s[0:4]
s[:3]
s[-5:-2]
s[0:6:2]

'pto'

In [ ]:
s="python"
s.capitalize()

'Python'

In [ ]:
s.upper()

'PYTHON'

In [ ]:
s_c=s.capitalize()
s_c
s_c

'Python'

In [ ]:
s_c=s_c.swapcase()
s_c

'pYTHON'

In [ ]:
#Boolean
X= True
Y= False
print(type(X))
print(type(Y))


<class 'bool'>
<class 'bool'>


In [ ]:
x= 123
bool(x)

True

In [ ]:
float("4.5")


4.5

In [ ]:
int("25")


25

In [ ]:
int(5.625)

5

In [ ]:
float(6)


6.0

In [ ]:
int(true)


NameError: name 'true' is not defined

In [ ]:
float(false)


NameError: name 'false' is not defined

In [ ]:
str(true)

NameError: name 'true' is not defined

In [ ]:

bool(0)


False

In [ ]:
bool("hello world")


True

In [ ]:
bool(223.5)

True

In [ ]:
2+4

6

In [ ]:

10%3

1

In [ ]:
10/3

3.3333333333333335

In [ ]:
10//3

3

In [ ]:
A=  10
A+=5
A
#

15

In [ ]:
B=10
B
A+B

25

#List, Tuples#


In [ ]:
to_buy = ["books","Eraser","pen","sharpner"]
to_buy

['books', 'Eraser', 'pen', 'sharpner']

In [ ]:


#updating the list
to_buy.append("scale")
to_buy

['books', 'Eraser', 'pen', 'sharpner', 'scale']

In [ ]:
#removing the list
to_buy.remove("scale")
to_buy

['books', 'Eraser', 'pen', 'sharpner']

In [ ]:
#inserting the list
to_buy.insert(0,"scale")
to_buy

['scale', 'books', 'Eraser', 'pen', 'sharpner']

In [ ]:
to_buy.pop()


'sharpner'

In [ ]:
to_buy

['scale', 'books', 'Eraser', 'pen']

In [ ]:
items=("books","Eraser","pen","sharpner")
items

('books', 'Eraser', 'pen', 'sharpner')

In [ ]:
items.append("chocolate")

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
# defining a set
ab = {1,1,1,1,"a","a","b","c"}
ab

{1, 'a', 'b', 'c'}

In [ ]:
#relational operators
a=5
b=3

In [ ]:
a>b

True

In [ ]:
a<b

False

In [ ]:
a>=b

True

In [ ]:
a==b

False

In [ ]:
a!=b

True

In [ ]:
a==5 and b<4

True

In [ ]:
a is 5

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-58-80e6b7447efe>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  a is 5


True

In [ ]:
a is not b

True

In [ ]:
A=10
B=15
if A>B:
  print("A is greater than B")
elif B>A:
  print("B is greater than A")
else:
  pass
  print("B is greater than A")

B is greater than A


In [ ]:
rate = int(input("Enter the amount:"))
is_emi_available = True
if rate <= 20000:
    print("I will buy the TV")
elif is_emi_available:
    print("I will buy the TV")
else:
    print("I will not buy it")

Enter the amount:


ValueError: invalid literal for int() with base 10: ''

In [ ]:
rate = int(input("Enter the amount:"))
emi_amount = 50000
if rate <= 20000:
    print("I will buy the TV")
elif rate < emi_amount:
    print("I will buy the TV")
else:
    print("I will not buy it")

In [ ]:
current_temp = int(input("Enter the temperature:"))
if current_temp < 20:
    print("I will take the umbrella")
elif current_temp > 20:
    print("I will not go")
else:
    print("I will not take the umbrella")

In [ ]:
A = int(input("Enter the amount A:"))
B = int(input("Enter the amount B:"))
C = int(input("Enter the amount C:"))
if A > B:
  if A > C:
    print("A is biggest")
elif B > C:
  if B > A:
    print("B is biggest")
else:
  print("C is biggest")

In [ ]:
A = int(input("Enter the amount A:"))
B = int(input("Enter the amount B:"))
C = int(input("Enter the amount C:"))
if A > B and A > C:
    print("A is biggest")
elif B > C and B > A:
    print("B is biggest")
else:
  print("C is biggest")

In [ ]:
# Odd even checker
A = int(input("Enter the number"))
if A % 2 == 0:
  print("A is Even")
else:
  print("A is odd")


In [ ]:
print("first line \nsecond line")
print("\t space here")
print("no space")

# Calculator App#
- Accept two values from user
- accept a choice from user 1=add,2 = subtract, 3= mul, 4 = divide
-perform operatio and show output

In [ ]:

A = int(input("Enter the first number A"))
B = int(input("Enter the second number B"))
print("enter : 1.+ \n 2.- \n 3.* \n 4./")
choice = int(input("choose: "))

if choice == 1:
  print(A+B)
elif choice == 2:
  print(A-B)
elif choice == 3:
  print(A*B)
elif choice == 4:
  print(A/B)
else:
  print("Error")

Enter the first number A


ValueError: invalid literal for int() with base 10: ''

In [ ]:
num = [1,2,3,4,5]
for i in num:
  print(i)

In [ ]:
range(5)

In [ ]:
for i in range(5):
  print(i)

In [ ]:

for i in range(1,6):
  print(i)

1
2
3
4
5


In [ ]:
for i in range(1,11,2):
  print(i)

1
3
5
7
9


In [ ]:
A = int (input("enter the input"))
for i in range(1,A):

  print(i)

enter the input20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
name = "hari"
for letter in name:
  print(letter)

h
a
r
i


In [ ]:
lista = [1,2,3,4,5,6]
name = "hari"
print(len(lista))
print(len(name))

6
4


In [ ]:
num = [1,2,3,4,5]
#for i in num:
#  print(i)
for i in range(0,len(num),2):
  print(i,num[i])

0 1
2 3
4 5


In [ ]:
## take input
# print sum of even number


A = int(input("Enter the number"))
result = 0
for i in range(0,A+1,2):
  result += i
  print(result)
print("The sum of even numbers from 0 to provided nymber is =", result)

Enter the number10
0
2
6
12
20
30
The sum of even numbers from 0 to provided nymber is = 30


In [ ]:
A = 10
while A > 0:
  print(A)
  A = A-1

10
9
8
7
6
5
4
3
2
1


In [ ]:
for i in range(10,-1,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1
0


In [ ]:
A = [52,35,88,47,33,49]
result = 0
for i in range(len(A)):
  result += A[i]
print(result)
print(result/len(A))


304
50.666666666666664


In [ ]:
a = [52,35,88,47,33,49]
result = 0
for A in a:
  result += A
print(result , result/len(a))


304 50.666666666666664


In [ ]:
a = [52,35,88,47,33,49]
result = 0
for A in a:
  result += A
  print(result , result/len(a))
# for nta akath run akkya process okka kaanikkum
# fornta porathananki ans mathram

52 8.666666666666666
87 14.5
175 29.166666666666668
222 37.0
255 42.5
304 50.666666666666664


In [ ]:
a = [52,35,88,47,33,49]
largest = 0
for number in a:
  if largest < number:
    largest = number
    print(largest)

52
88


In [ ]:
a = [52,35,88,47,33,49]
smallest = 99999999
for number in a:
  if smallest > number:
      smallest = number
print(smallest)

33


In [ ]:
print("Type exit to stop")
a = input("Type here:")
while a!= "exit":
  a = input("Type again:")
  a = a.lower()

Type exit to stop
Type here:exit


In [ ]:
a = input("enter your password")
a


enter your passwordAdith


'Adith'

In [ ]:
b = input("enter the password")
while b!= a:
  print("incorrect password")
  b = input("try again")
print("Access granted")


enter the passwordAdith
Access granted


In [ ]:
for i in range(1,4):
  if i%5 == 0:
    break
  print(i)

1
2
3


In [ ]:
A = int(input("Enter the first number A"))

print("enter : 1.+ \n 2.- \n 3.* \n 4./ \n.exit")
choice = int(input("choose:"))
B = int(input("Enter the second number B"))
while True:

  if choice == 1:
    print(A+B)
  elif choice == 2:
    print(A-B)
  elif choice == 3:
    print(A*B)
  elif choice == 4:
    print(A/B)
  elif choice == 5:
    print("exiting.....20")
    break
  else:
    print("Error")
  choice = int(input("choose"))
A = int(input("Enter the first number A"))
B = int(input("Enter the second number B"))
choice = int(input("choose:"))

Enter the first number A10
enter : 1.+ 
 2.- 
 3.* 
 4./ 
.exit
choose:1
Enter the second number B20
30
choose5
exiting.....20
Enter the first number A10
Enter the second number B20
choose:2


In [ ]:
# continue
for i in range(13):
  if i%3 == 0:
    print("multiple of 3 skipping")
    continue
  print(i)

multiple of 3 skipping
1
2
multiple of 3 skipping
4
5
multiple of 3 skipping
7
8
multiple of 3 skipping
10
11
multiple of 3 skipping


In [ ]:
 def hello(name):
  print("hello",adi)

In [ ]:
hello

<function __main__.hello(name)>

In [ ]:
def add(n1,n2):
  result = n1+n2
  print(result)
  # print(n1+n2)

In [ ]:
num1 = 20
num2 = 20
add(num1,num2)

40


In [ ]:
def return_sum(n1,n2):
  result = n1+n2
  return result

In [ ]:
a = return_sum(10,20)

In [ ]:
def odd_even(N):
  if N%2==0:
    print("even")

  else:
      print("odd")

odd_even(123)

odd


In [ ]:
def odd_even_return(N):
  if N%2==0:
    return("even")
  return("odd")

output = odd_even_return(9)

print(output)

odd


In [ ]:
def small_and_large(list_a):
  small = min(list_a)
  large = max(list_a)
  return small,large
out = small_and_large([1,23,434,667,-11])
print(out[0],out[1])

-11 667


In [ ]:
def addi(X,Y):
  print(X+Y)
def subt(X,Y):
  print(X-Y)
def mult(X,Y):
  print(X*Y)
def divi(X,Y):
  print(X/Y)

A = int(input("Enter the first number A"))
B = int(input("Enter the second number B"))
print("enter : 1.+ \n 2.- \n 3.* \n 4./ \n.exit")
choice = int(input("choose:"))

while True:

  if choice == 1:
    addi(A,B)
  elif choice == 2:
    subt(A,B)
  elif choice == 3:
    mult(A,B)
  elif choice == 4:
    divi(A,B)
  elif choice == 5:
    print("exiting.....20")
    break
  else:
    print("Error")


Streaming output truncated to the last 5000 lines.
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-10
-

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-f2a47a07aa60>", line 20, in <cell line: 15>
    subt(A,B)
  File "<ipython-input-1-f2a47a07aa60>", line 4, in subt
    print(X-Y)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 402, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/iostream.py", line 203, in schedule
    self._event_pipe.send(b'')
  File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/socket.py", line 620, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 746, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 793, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/sock

TypeError: object of type 'NoneType' has no len()

In [ ]:
BMI = []
Height = [1.10 , 1.12 , 1.14 , 1.16 , 1.18 , 1.20 , 1.22 , 1.24 , 1.26 , 1.28]
Weight = [ 50 , 60 , 50 , 80 , 95 , 54 , 75 , 65 , 45 , 85 ]
#BMI = (Height/Weight)^2

for H,W in zip(Height , Weight):
  BMI_CAL = (W/H**2)
  BMI.append(BMI_CAL)
  print(BMI)



[41.32231404958677]
[41.32231404958677, 47.83163265306122]
[41.32231404958677, 47.83163265306122, 38.473376423514935]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847, 37.5]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847, 37.5, 50.389680193496375]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847, 37.5, 50.389680193496375, 42.27367325702393]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847, 37.5, 50.389680193496375, 42.27367325702393, 28.344671201814055]
[41.32231404958677, 47.83163265306122, 38.473376423514935, 59.45303210463734, 68.22752082734847, 37.5, 50.389680193496375, 42.27367325702393, 28.344671201814055, 51.8798828125]


In [ ]:
import numpy as np

In [ ]:
 height_arr = numpy.array(Height)

In [ ]:
weight_arr = numpy.array(Weight)

In [ ]:
arr_2d = np.array([[4 , 5 , 6 , 7],
                   [1 , 2 , 3 , 4]])

In [ ]:
arr_2d.ndim

2

In [ ]:
arr_2d.shape

(2, 4)

In [ ]:
ran_arr = np.arange(3,40)

In [ ]:
ran_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [ ]:
ran_arr = np.arange(0,16)


In [ ]:
ran_arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:

ran_arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
ran_arr.max()

15

In [ ]:
ran_arr.mean()

7.5

In [ ]:
ran_arr.min()

0

In [ ]:
zer_arr = np.zeros((4,4))

In [ ]:
zer_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr_uni = np.random.rand(5)

In [ ]:
arr_uni

array([0.39797931, 0.9984043 , 0.5911469 , 0.68640199, 0.02044941])

In [ ]:
from numpy import random

In [ ]:
testarr = np.arange(0,16,2)

In [ ]:
testarr

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
testarr1 = testarr>10


In [ ]:
testarr[testarr1]

array([12, 14])

#PANDAS#

In [ ]:
import pandas as pd

In [ ]:

randnum = pd.Series([1 , 2 , 3 , -45])

In [ ]:
randnum

0     1
1     2
2     3
3   -45
dtype: int64

In [ ]:
randnum.values

array([  1,   2,   3, -45])

In [ ]:
randnum.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
randseries = pd.Series([34,56,78,90],index = ['a' , 'b' , 'c' , 'd'])

In [ ]:

randseries


a    34
b    56
c    78
d    90
dtype: int64

In [ ]:
data = {"India":500, "France":400, "England": 799}

In [ ]:
pd.Series(data)

India      500
France     400
England    799
dtype: int64

In [ ]:
city2  = pd.Series([12,-6,8,-3], index=["day1","day2","day3","day4"])

In [ ]:
city2


day1    12
day2    -6
day3     8
day4    -3
dtype: int64

In [ ]:
city2[["day1","day2"]]

day1    12
day2    -6
dtype: int64

In [ ]:
city2>0

day1     True
day2    False
day3     True
day4    False
dtype: bool

In [ ]:
city2[city2>0]

day1    12
day3     8
dtype: int64

In [ ]:
data = {"India":950, "France":400, "England": 800, "China":900, "Japan":200}

In [ ]:
data = {"India": 950, "France": 400, "England": 800, "China": 900, "Japan": 200}

for country, value in data.items():
  print(value)

  if value > 200 and value < 400:
    print(f"{country}: {value}")

950
400
800
900
200


200

In [ ]:
states = ["Andhra", "delhi","tn","mp","kerala","karnataka"]

In [ ]:
data = {"year": 2000,2001,2002,2004,2005,2006}
"states":["Andhra", "delhi","tn","mp","kerala","karnataka"]
pop

SyntaxError: ':' expected after dictionary key (<ipython-input-1-052a2133cfb1>, line 1)